theme: jekyll-theme-slate
name: Tilmann Rabl
markdown: kramdown

collections:
  publications:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publications
